version: '3.7'

networks:
  vault:
    ipam:
      driver: default
      config:
        - subnet: "10.5.0.0/16"

services:
  vault_c1_s1:
    image: hashicorp/vault-enterprise:latest
    #image: hashicorp/vault:latest
    restart: always
    volumes:
      - ./vault_c1/vault_c1_s1:/vault/config:rw
      - /vault/data
      - /etc/vault/logs
    ports:
      - "18201:8200/tcp"
    cap_add:
      - IPC_LOCK
    container_name: vault_c1_s1
    entrypoint: "vault server -config=/vault/config"
    networks:
      - vault

  vault_c1_s2:
    image: hashicorp/vault-enterprise:latest
    #image: hashicorp/vault:latest
    restart: always
    volumes:
      - ./vault_c1/vault_c1_s2:/vault/config:rw
      - /vault/data
      - /etc/vault/logs
    ports:
      - "18202:8200/tcp"
    cap_add:
      - IPC_LOCK
    container_name: vault_c1_s2
    entrypoint: "vault server -config=/vault/config"
    networks:
      - vault

  vault_c1_s3:
    image: hashicorp/vault-enterprise:latest
    #image: hashicorp/vault:latest
    restart: always
    volumes:
      - ./vault_c1/vault_c1_s3:/vault/config:rw
      - /vault/data
      - /etc/vault/logs
    ports:
      - "18203:8200/tcp"
    cap_add:
      - IPC_LOCK
    container_name: vault_c1_s3
    entrypoint: "vault server -config=/vault/config"
    networks:
      - vault

  vault_c2_s1:
    image: hashicorp/vault-enterprise:latest
    #image: hashicorp/vault:latest
    restart: always
    volumes:
      - ./vault_c2/vault_c2_s1:/vault/config:rw
      - /vault/data
      - /etc/vault/logs
    ports:
      - "28201:8200/tcp"
    cap_add:
      - IPC_LOCK
    container_name: vault_c2_s1
    entrypoint: "vault server -config=/vault/config"
    networks:
      - vault

  vault_c2_s2:
    image: hashicorp/vault-enterprise:latest
    #image: hashicorp/vault:latest
    restart: always
    volumes:
      - ./vault_c2/vault_c2_s2:/vault/config:rw
      - /vault/data
      - /etc/vault/logs
    ports:
      - "28202:8200/tcp"
    cap_add:
      - IPC_LOCK
    container_name: vault_c2_s2
    entrypoint: "vault server -config=/vault/config"
    networks:
      - vault

  vault_c2_s3:
    image: hashicorp/vault-enterprise:latest
    #image: hashicorp/vault:latest
    restart: always
    volumes:
      - ./vault_c2/vault_c2_s3:/vault/config:rw
      - /vault/data
      - /etc/vault/logs
    ports:
      - "28203:8200/tcp"
    cap_add:
      - IPC_LOCK
    container_name: vault_c2_s3
    entrypoint: "vault server -config=/vault/config"
    networks:
      - vault

  vault_c3_s1:
    image: hashicorp/vault-enterprise:latest
    #image: hashicorp/vault:latest
    restart: always
    volumes:
      - ./vault_c3/vault_c3_s1:/vault/config:rw
      - /vault/data
      - /etc/vault/logs
    ports:
      - "38201:8200/tcp"
    cap_add:
      - IPC_LOCK
    container_name: vault_c3_s1
    entrypoint: "vault server -config=/vault/config"
    networks:
      - vault

  vault_c3_s2:
    image: hashicorp/vault-enterprise:latest
    #image: hashicorp/vault:latest
    restart: always
    volumes:
      - ./vault_c3/vault_c3_s2:/vault/config:rw
      - /vault/data
      - /etc/vault/logs
    ports:
      - "38202:8200/tcp"
    cap_add:
      - IPC_LOCK
    container_name: vault_c3_s2
    entrypoint: "vault server -config=/vault/config"
    networks:
      - vault

  vault_c3_s3:
    image: hashicorp/vault-enterprise:latest
    #image: hashicorp/vault:latest
    restart: always
    volumes:
      - ./vault_c3/vault_c3_s3:/vault/config:rw
      - /vault/data
      - /etc/vault/logs
    ports:
      - "38203:8200/tcp"
    cap_add:
      - IPC_LOCK
    container_name: vault_c3_s3
    entrypoint: "vault server -config=/vault/config"
    networks:
      - vault
